@baseUrl = http://localhost:4300/api

### Register
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
    "name": "Test User",
    "email": "test@example.com",
    "password": "Password123!"
}

### Login First
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "Password123!"
}

### Get Users
@token = {{login.response.body.data.accessToken}}
GET {{baseUrl}}/users
Authorization: Bearer {{token}}

### Refresh Token
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{login.response.body.data.refreshToken}}"
}

### Logout
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{login.response.body.data.accessToken}} 