@baseUrl = http://localhost:4300/api

### Request Password Reset
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json

{
    "email": "test@example.com"
}

### Reset Password
POST {{baseUrl}}/auth/reset-password/c42116d5b120249e2a4ad1530caf8eb244bf61087f588d1f62610596f5cfb090
Content-Type: application/json

{
    "password": "NewPassword123!"
} 